In [54]:
import numpy as np

R = np.arange(6*5)

j = np.array(range(1,7))
a = np.array(range(2,7))
#print(j)
#print(a)
    
counter = 0
for m in a:
    for n in j:
        tmp = pow(m,n)%7
        R[counter] = tmp
        counter = counter + 1

R2 = R.reshape(5,6)  
print(R2)


[[2 4 1 2 4 1]
 [3 2 6 4 5 1]
 [4 2 1 4 2 1]
 [5 4 6 2 3 1]
 [6 1 6 1 6 1]]
